# HAHHA INI UPDATE .TMUX.CONF
# basic settings
set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 0
unbind r
bind r source-file ~/.tmux.conf

# vim keybinding
# setw -g mode-keys vi

# Visual mode like Vim
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi r send -X rectangle-toggle

# Vim movement keys
bind -T copy-mode-vi h send -X cursor-left
bind -T copy-mode-vi j send -X cursor-down
bind -T copy-mode-vi k send -X cursor-up
bind -T copy-mode-vi l send -X cursor-right

# ==============================
#  RESIZE PANE (H J K L)
# ==============================

bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5


# status bar
set -g status on
set -g status-interval 2
set -g status-position top
set -g status-bg black
set -g status-fg white

set -g status-left-length 40
set -g status-left ' #S '
set -g status-right-length 100
set -g status-right ' %Y-%m-%d | %H:%M '

# ==============================
#  WINDOW & PANE SETTINGS
# ==============================

setw -g automatic-rename on
set -g allow-rename off
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour45


# System Clipboard
# Linux (xclip)
if -b 'command -v xclip' 'bind C-y run "tmux save-buffer - | xclip -selection clipboard"'
# WSL (clip.exe)
if -b '[ -n \"$WSL_DISTRO_NAME\" ]' 'bind C-y run "tmux save-buffer - | clip.exe"'

# Aktifkan vi mode untuk copy mode
setw -g mode-keys vi

# Binding untuk masuk copy mode (opsional, default sudah Ctrl+b [)
bind [ copy-mode

# Binding tambahan untuk copy mode ala vim (opsional tapi recommended)
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle
