
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.85
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Bold"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

size = 12

[general]
import = [
    "~/AppData/Roaming/alacritty/alacritty/themes/coolnight.toml"
]

[terminal]

[terminal.shell]
program = "wsl.exe"
args = ["-d", "Ubuntu-22.04", "--cd", "~"]
